Throws exc to view
InKastraRedBrother/Dictionary pull request #9
Opened 2022-06-03 12:20 UTC by InKastraRedBrother

2022-06-03 13:57 UTC, akarasev13 commented on src/main/java/dictionary/service/Service.java
>      public boolean deleteRow(String key) throws Exception {
почкму Exception?

2022-06-03 13:59 UTC, akarasev13 commented on src/main/java/dictionary/view/ViewDictionary.java
> +                        System.out.println(key + ":" + value + " added");
и все еще неименованные константы..

2022-06-06 11:47 UTC, Belatrya requested changes

2022-06-06 11:47 UTC, Belatrya commented on src/main/java/dictionary/exception/SomeKindOfError.java
> +public class SomeKindOfError extends RuntimeException{
Добавить java-doc. Название не раскрывает сути ошибки. В тексте ошибки у тебя хотя бы о словаре что-то сказано. Ты наследуешься от `exception `а называешь `Error`, тут может быть недопонимание, `error `это об ошибках с памятью и подобные технические вещи.

2022-06-06 11:47 UTC, Belatrya commented on src/main/java/dictionary/service/Service.java
> +    public String showAllRows() throws SomeKindOfError {
Ты отнаследовался от рантайм эксепшена, а это непроверяемое исключение, не надо его тут (и дальше по этому файлу) пробрасывать дальше, компилятор этого не требует, тебе нужно только найти место где его обработать.

2022-06-06 11:47 UTC, Belatrya commented on src/main/java/dictionary/service/Service.java
> +    public boolean addRow(String key, String value) throws SomeKindOfError {
см выше

2022-06-06 11:47 UTC, Belatrya commented on src/main/java/dictionary/service/Service.java
> +    public boolean deleteRow(String key) throws SomeKindOfError {
см выше

2022-06-06 11:47 UTC, Belatrya commented on src/main/java/dictionary/service/Service.java
> +    public String searchRow(String key) throws SomeKindOfError {
см выше

2022-06-06 12:20 UTC, merged